### ISSUE TITLE
XBMC Module is not working in any ANDROID Device.

### ISSUE THREAD

**Issue by luckyahuja** [CommandFusion/iViewer-For-Android#136]
hi guys,, i am facing a problem in xbmc module, xbmc module is not working in any ANDROID device, i chek with all JELLY BEAN and all ICE CREAM SANDWICH versions, in mean time it is working fine in IOS devices. i am using guiDesigner version 2.7.0.713, and using Iviewer version in ANDROID 4.0.177.

**Comment by CF-Terence** [comment]
Could be due to the difference of how HTTP request is processed between IOS and Android devices.

Tried adding in the additional headers and user-agent string for your device? Something like 
var custom_header = {
                "content-type": "application/json",
                "user-agent": "Dalvik/1.6.0 (Linux; U; Android 4.1.1; GT-P3110 Build/JRO03C)"
            };
CF.request(host, "POST", custom_header, JSON.stringify(json), function(status, headers, body) {
},

Check here for more previous discussion on this :
https://groups.google.com/forum/#!searchin/commandfusion/xbmc$20for$20android/commandfusion/TZ3UBSorD8w/A02bWif4glcJ

**Comment by CF-Terence** [comment]
Issue resolved by adding in the custom header and user-agent in the CF.request function. Try changing the user-agent according to the control device if still not working.
