### ISSUE TITLE
subpages are been overlapped

### ISSUE THREAD

**Issue by ucbrasil** [CommandFusion/iViewer-For-Android#20]
when I call a new subpage, the old one doesn´t disapear (made with a macro that set one digital join to 1 and the others to 0). I used as a test a project that works good on iPhone.

Phone: Galaxy Android V2.3.4 user:automacao@uc-brasil.com (at the moment without a license)
iViewer-beta-81.apk 

http://dl.dropbox.com/u/23807396/galaxy_debug.zip

**Comment by fpillet** [comment]
Thank you, I think this is an issue specific to 2.x. Will fix it, thanks for providing a test GUI

**Comment by fpillet** [comment]
Fixed some issues for next build. This said, there are many problems with your GUI:
- you don't have a background theme in any of your pages
- your TV button is on the same join as the subpage. Since this is not a toggle, pressing the button shows the subpage (starts animation), releasing hides the subpage (start animation) but then you execute a command that itself shows the subpage.

Fix these problems, and things will be much smoother for you.

**Comment by ucbrasil** [comment]
ok, thanks , I will revise the gui. 
The fact that it doesn´t have a background is this is a test gui, only to show you the problem.  
About the join, I will use another join number to the TV button, different to tv subpage join number. Thanks for he tip.
