### ISSUE TITLE
Issue #30 update - slow responsiveness

### ISSUE THREAD

**Issue by sdomotica** [CommandFusion/iViewer-For-Android#35]
The Issue Button on list and subpage. Work with 84 version.

The problem is that the button has slow responsiveness resptect at the same button out.

Please test the gui of issue #30 for note it.

Bye
Sandro

**Comment by fpillet** [comment]
This is normal. There is a slight delay when you tap on something in a list, which leaves time to determine whether this is going to be a list scroll, or a real tap on the button. I can reduce the delay a bit but we need to keep some delay

**Comment by sdomotica** [comment]
Same delay as iOS? I tried the same GUI on iPad, and it here is acceptable.
Bye
Sandro

**Comment by ucbrasil** [comment]
same on me. If I press the button and wait a few seconds, the macro is called and, in my case, the new subpage is showed. 

The problem is that the user hears the press sound to early and release the button before wait the necessary time to call the command.

http://dl.dropbox.com/u/23807396/galaxy_debug.zip
This test project works fine on iPod
