### ISSUE TITLE
Trouble with CF on Dell Streak 5 with android 2.3

### ISSUE THREAD

**Issue by Scaramush** [CommandFusion/iViewer-For-Android#39]
I try to design GUI for  HDL hardware and on iPad2 all buttons work correct. On Streak no one button works

**Comment by jarrodbell** [comment]
Please provide more details. This is a very vague report.

**Comment by Scaramush** [comment]
What kind of detailes? I'm new in CF so I didn't now how I can receive log from it. GUI I sent to support email with theme that contains issue number

**Comment by jarrodbell** [comment]
What do you mean "no buttons work" - can you explain exactly what doesn't work? Buttons can do a lot of things, so need exact details on what the problem is.

**Comment by Scaramush** [comment]
this buttons and sliders must control HDL relay and dimmer. And hardware didn't do anything. Also I tried Your beta GUI for xbmc (add JS file to my GUI and add "up", "down", "left", "right" and "ok" buttons with JS as command), on iPad it worked - I can move cursor left-right up-down. On Dell Streak didn't work.

**Comment by jarrodbell** [comment]
So to be more specific, are you saying the some commands are not being sent from button presses? And these exact commands work on iPad? Have you tried without your iPad connected to the system? Maybe it only accepts one connection at a time. We really need specific data rather than general "the hardware didn't do anything".

**Comment by fpillet** [comment]
Scaramush, thank you for reporting your issue. Unfortunately, you are not providing enough information for us to understand exactly what your problem is. Additionally, we need all the information you can provide: device brand / model / OS version, the GUI file that doesn't work, etc.

To be able to troubleshoot your problem and confirm a bug, we need as much information as you can provide to us. This beta testing phase requires some advanced experience of iViewer, including testers ability to troubleshoot issues.

If you feel you're too new to CF, please wait for the beta phase to advance to a more ready state, which we'll announce on the google group.

**Comment by Scaramush** [comment]
Yes, exactly, I think nothing been sent from button pressed

Yes, I tried connect from android device without iPad connected to the system. Nothing happens

**Comment by Scaramush** [comment]
fpillet, I sent GUI to support email when open this issue (subject is "#39") . My device is Dell Sreak 5 with android 2.3.3. But how can I troubleshoot issue if remote debugging do nothing and there is no any logs from beta relise?

**Comment by jarrodbell** [comment]
I don't have a copy of this email. Can you send it again?

**Comment by Scaramush** [comment]
Ok, I sent it again

**Comment by fpillet** [comment]
That's the hard part: troubleshooting when you don't have a remote debugger yet :-) it's a mix of guesswork, experience and some network sampling tools that can help determine what exactly is happening.

**Comment by Scaramush** [comment]
well, I use sniffer to control packets, that are sent. And there is no packets from Streak IP. And if I try iPad - I see all it packets

**Comment by fpillet** [comment]
Ah this is a useful bit of info. We'll look into your GUI and let you know what we find, thanks!

**Comment by Scaramush** [comment]
After reflashing of Dell Streak all work correct. So, this issue can be close
